### PR TITLE
Rename view usage/references to template

### PR DESCRIPTION
**Pull request by AD7six**
The current Template task, is renamed BakeTemplate; the current view task is renamed Template task.

Ref: https://github.com/cakephp/bake/issues/2

### CODE REVIEW

**Comment by AD7six** [comment]
@josegonzalez Need to coordinate merging this one ot prevent migrations breaking.

**Comment by markstory** [comment]
It would be nice to leave a stub ViewTask so people can find out what the new command name is.

**Comment by AD7six** [comment]
I'm not sure that's a good idea.

You can't right now bake a view class, and unless the syntax changes, that would block adding that possibility.

**Comment by AD7six** [comment]
I can do this if we do want to point users in the right direction:

```
diff --git src/Shell/BakeShell.php src/Shell/BakeShell.php
index ecc6845..d35de60 100644
--- src/Shell/BakeShell.php
+++ src/Shell/BakeShell.php
@@ -72,6 +72,16 @@ class BakeShell extends Shell
      */  
     public function main()
     {   
+        if ($this->args && $this->args[0] === 'view') {
+            $this->out('<error>The view command has been renamed</error>');
+            $this->out('To create template files, use the template task:', 2);
+            $args = $this->args;
+            array_shift($args);
+            $args = implode($args, ' ');
+            $this->out(sprintf('    bin/cake bake template %s', $args), 2);
+            return false;
+        }
+
         $connections = ConnectionManager::configured();
         if (empty($connections)) {
             $this->out('Your database configuration was not found.');
```

**Comment by markstory** [comment]
@AD7six I think that warning is enough.

**Comment by antograssiot** [comment]
:+1: 
I've done some docs update proposal regarding this modification.

**Comment by AD7six** [comment]
@antograssiot awesome, thanks!

**Pull request merged**
