### PR TITLE
Remove plugin installer dependency

### PR DESCRIPTION
**Pull request by AD7six**
cakephp/app requires this, so plugins don't have to.

Depends on cakephp/app#216

### CODE REVIEW

**Comment by ADmad** [comment]
@AD7six Doesn't composer complain about not finding an installer for type "cakephp-plugin" ?

**Comment by AD7six** [comment]
@ADmad no:

```
www-data @ dev [ /tmp/app ] (master *%)
-> cat composer.json 
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "http://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.4.16",
        "cakephp/cakephp": "3.0.*-dev",
        "cakephp/bake": "no-plugin-installer-dev",
        "cakephp/plugin-installer": "dump-autoload-hook-dev"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump"
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
}
www-data @ dev [ /tmp/app ] (master *%)
-> composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing aura/installer-default (1.0.0)
    Loading from cache

  - Installing cakephp/plugin-installer (dev-dump-autoload-hook 3766e30)
    Cloning 3766e307de2133fb893036b9e51fa7dd5fb8634b

  - Installing nesbot/carbon (1.13.0)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Installing aura/intl (1.1.1)
    Loading from cache

  - Installing ircmaxell/password-compat (v1.0.4)
    Loading from cache

  - Installing cakephp/cakephp (3.0.x-dev acbe91f)
    Cloning acbe91f9c5171aae4e153ac985d9cbfb64263750

  - Installing cakephp/bake (dev-no-plugin-installer b3ae81b)
    Cloning b3ae81b0db677b4ed5da9ab64e150620cf67fb12

Writing lock file
Generating autoload files
Set Folder Permissions ? (Default to Y) [Y,n]? n
No Security.salt placeholder to replace.
www-data @ dev [ /tmp/app ] (master *%)
-> bin/cake bake

Welcome to CakePHP v3.0.0-RC1 Console
---------------------------------------------------------------
App : src
Path: /tmp/app/src/
---------------------------------------------------------------
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- fixture
- test
- view
- behavior
- helper
- shell
- controller
- model
- plugin
- project
- cell
- component

By using `cake bake [name]` you can invoke a specific bake task.
www-data @ dev [ /tmp/app ] (master *%)
-> 
```

**Comment by ADmad** [comment]
@AD7six Cool.

**Comment by AD7six** [comment]
I'm going to merge this one, as so long as _any_ composer project makes a reference to the plugin installer it will be installed and used.

**Pull request merged**
