### PR TITLE
Update testsuite to use new fixtures system.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by othercorey** [comment]
Looks good to me. We should follow up by cleaning out the fixture fields unless we have to support users referencing bake fixtures.

**Comment by ADmad** [comment]
> We should follow up by cleaning out the fixture fields unless we have to support users referencing bake fixtures.

It's a possibility, so let's just keep them for now.

**Comment by othercorey** [comment]
I might have merged this too soon, but can fix in a follow up. The core fixtures that are referenced in tests should be copied into Bake since the schema is no longer defined by the fixture.

**Comment by ADmad** [comment]
Ah right, I forgot that too.

**Pull request merged**
