### PR TITLE
RFC: Remove the project task

### PR DESCRIPTION
**Pull request by AD7six**
When bake was part of cakephp/cakephp - it arguably made sense. But now
that it's a seperate plugin I don't think so.

To use the project task, users would need to EITHER:

    composer create-project cakephp/app whatever
    cd whatever
    bin/cake bake project /another/project

OR

    download a zipball
    cd whatever
    bin/cake bake project /another/project

Instead of just:

    composer create-project cakephp/app /another/project

the project task wouldn't work anyway if composer wasn't installed, so
it doesn't provide that crutch to users anyway.

### CODE REVIEW

**Comment by antograssiot** [comment]
:+1: for removing this

**Comment by ADmad** [comment]
:+1:

**Comment by rchavik** [comment]
:+1:

**Comment by dakota** [comment]
:+1:

**Comment by DSchalla** [comment]
Makes perfect sense.

**Pull request merged**
