### PR TITLE
remove parent::buildOptionParser()

### PR DESCRIPTION
**Pull request by saeideng**
I think calling parent is redundant
I will fix testCases

### CODE REVIEW

**Comment by dereuromark** [comment]
Dont we always do that? this makes it easier to extend by adding something in between, you never know what the parent added.

**Comment by saeideng** [comment]
> Dont we always do that?

always ? :thinking:  nope 
```php
use Cake\Command\Command;
class MyCommand extends Command
```
`MyCommand` first extends `Cake\Command\Command` that has not `buildOptionParser()` and then 
 `Cake\Console\BaseCommand` 

`parent::buildOptionParser()` in baked commands refers to `Cake\Console\BaseCommand` 
```php
    protected function buildOptionParser(ConsoleOptionParser $parser): ConsoleOptionParser
    {
        return $parser;
    }
```

**Comment by dereuromark** [comment]
My point is:
It is the same as with events and other extension points.
Calling parent is just a good default as it will also take into consideration any addition there, at the point in time or later.
Finding the issues after the fact is much harder if we remove those IMO.

**Comment by ADmad** [comment]
As stated by @dereuromark calling parent's method is a good default, there's no need to change that.

**Pull request closed without merging**
