### PR TITLE
ignore shadow translations tables *_translations

### LINKED ISSUE #1011: Skip table class generation for `*_translations` table.
### Description

The `TableScanner` class needs to be updated to ignore shadow translations tables `*_translations`, we don't to generate table classes for them.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/bake/issues/1011

We probably want to document that we cannot bake any actual tables anymore that would end this way.
I have for example
https://github.com/dereuromark/cakephp-translate/blob/734d8610e6de7b81878052546890a55662e52eda/config/Migrations/20170414190437_TranslateCache.php#L11
which would then not work anymore.

Is there a way we could be more specific maybe?
Intospecting the table schema to see if it matches a shadow table schema might be overkill, no?

### CODE REVIEW

**Comment by ADmad** [comment]
> Intospecting the table schema to see if it matches a shadow table schema might be overkill, no?

It would be a foolproof way though as shadow tables have a multicolumn PK with a `locale` column.

Another simpler option would be to check if a matching table without the `_translations` suffix also exists.

**Comment by dereuromark** [comment]
Either way, then the regexp and $ignore seems not to cover it anymore here.
I made its own method now.

**Review by ADmad — APPROVED** [review]

**Review by ADmad — CHANGES_REQUESTED** [review]
I just realized something. Skipping the shadow tables should be done in the `ModelAllCommand`, not the `TableScanner`.

I have my own customized model command where I check if the tables list returned by the `TableScanner` has a matching shadow table for a table and add the `Translate` behavior for it. So removing these tables from the tables list itself will break that feature.

**Comment by dereuromark** [comment]
Better?

**Comment by dereuromark** [comment]
However, it would still bake
- Table
- Entity
- Controller
- ...

when running through "bake all --everything" etc
so this then needs to be duplicated across mutliple ones :/

**Review by ADmad — APPROVED** [review]

**Comment by ADmad** [comment]
In that case keep the `removeShadowTranslationTables()` in `TableScanner` itself but call in from `ModelAllCommand`, `ControllerAllCommand` and `AllCommand`?

**Comment by dereuromark** [comment]
Now it works properly :tada:

**Pull request merged**
