### PR TITLE
Add a basic OptionParser into the baked shell, for ease of customisation

### PR DESCRIPTION
**Pull request by davidyell**
I always have to look this up, so figured it'd sure be handy to have it right there in the baked shell with a link to the docs.

I have run the test suite and everything passed. Let me know if you'd like me to make an attempt at including a new test case.

### CODE REVIEW

**Comment by markstory** [comment]
I like the change, but the tests will need to be updated.

**Comment by davidyell** [comment]
The tests are not failing because of my pull request. They are failing for other reasons. @markstory please can you clarify if you want me to add a new test case or not. Fixing the failing Travis is outside the scope of this PR.

The test suite passes locally
Terminal

**Comment by chinpei215** [comment]
I could reproduce the test failing on **master**. So it is not related with this PR.
bake-error

**Comment by markstory** [comment]
@chinpei215 Interesting, the tests passed for me locally using sqlite. I'll take a look tonight at home with a postgres db.

**Comment by markstory** [comment]
Postgres tests should be fixed with #230

**Comment by davidyell** [comment]
Thanks @markstory :+1: :tada:

**Pull request merged**
