### PR TITLE
Visual break for behaviours

### PR DESCRIPTION
**Pull request by davidyell**
I think it is far easier to read with a visual break between the table setup, behaviour and associations.

### CODE REVIEW

**Comment by bcrowe** [comment]
The test comparison templates need updated. Also, I'd only include the 2nd line break if `$associations` isn't empty.

**Comment by davidyell** [comment]
Righto, will fix!

**Comment by davidyell** [comment]
I haven't forgotten, just had a busy week.

**Comment by bcrowe** [comment]
Awesome! Thanks! :+1:

**Pull request merged**
