### PR TITLE
Remove _serialize from templates

### PR DESCRIPTION
**Pull request by cleptric**
cc @chinpei215

### CODE REVIEW

**Comment by markstory** [comment]
Is this necessary with the auto serialize removed from the app skeleton?

**Comment by chinpei215** [comment]
I think it is necessary. I think people would easy to forget to remove this code from the baked controller. For instance, our official site has not removed the code: https://github.com/cakephp/cakephp.org/blob/e4471d274571e4c9fc9581816077cb54063609e8/src/Controller/Admin/ProjectsController.php#L34
I don't think it is intended to return JSON/XML from the action. And it could be a security hole if we had authorization based on roles.

**Comment by chinpei215** [comment]
We should recognize this as a potential security risk. In fact, we have already recommended to remove all` _serialize` from actions. So first, I think we should remove `_serialize` as soon as possible. And if you have some ideas about the new option, we can add it and its documentation.

**Comment by rchavik** [comment]
i agree with@chinpei215

**Comment by markstory** [comment]
@rchavik @chinpei215 Ok.

**Pull request merged**
