### PR TITLE
4.x remove subcommand

### PR DESCRIPTION
**Pull request by saeideng**
Refs: https://github.com/cakephp/cakephp/pull/13194

output:
```
# bin/cake bake --help
Current Paths:

* app:  src
* root: ...bake
* core: ...bake/vendor/cakephp/cakephp

Available Commands:

App:
 - bake command
 - bake shell
 - bake shell_helper

Bake:
 - bake all
 - bake behavior
 - bake cell
 - bake component
 - bake controller
 - bake controller all
 - bake fixture
 - bake fixture all
 - bake form
 - bake helper
 - bake mailer
 - bake middleware
 - bake model
 - bake model all
 - bake plugin
 - bake task
 - bake template
 - bake template all
 - bake test

To run a command, type `cake command_name [args|options]`
To get help on a specific command, type `cake command_name --help`
```

@markstory how we can move bellow lists to `bake` section?
```
App:
 - bake command
 - bake shell
 - bake shell_helper
```

also description does not show now

### CODE REVIEW

**Comment by markstory** [comment]
I think classname grouping is done based on classname/namespace. I can look into why those aren't getting grouped correctly.

**Comment by saeideng** [comment]
@markstory 
```php
debug($commands)
//
[
	'bake mailer' => 'Bake\Command\MailerCommand',
	'bake all' => 'Bake\Command\AllCommand',
	'bake helper' => 'Bake\Command\HelperCommand',
	'bake middleware' => 'Bake\Command\MiddlewareCommand',
	'bake template all' => 'Bake\Command\TemplateAllCommand',
	'bake fixture' => 'Bake\Command\FixtureCommand',
	'bake component' => 'Bake\Command\ComponentCommand',
	'bake task' => 'Bake\Command\TaskCommand',
	'bake plugin' => 'Bake\Command\PluginCommand',
	'bake form' => 'Bake\Command\FormCommand',
	'bake template' => 'Bake\Command\TemplateCommand',
	'bake fixture all' => 'Bake\Command\FixtureAllCommand',
	'bake test' => 'Bake\Command\TestCommand',
	'bake command' => 'Bake\Command\CommandCommand',
	'bake controller all' => 'Bake\Command\ControllerAllCommand',
	'bake model all' => 'Bake\Command\ModelAllCommand',
	'bake behavior' => 'Bake\Command\BehaviorCommand',
	'bake cell' => 'Bake\Command\CellCommand',
	'bake controller' => 'Bake\Command\ControllerCommand',
	'bake shell_helper' => 'Bake\Command\ShellHelperCommand',
	'bake model' => 'Bake\Command\ModelCommand',
	'bake shell' => 'Bake\Command\ShellCommand'
]

**Comment by saeideng** [comment]
grouping issue can now fix by https://github.com/cakephp/cakephp/commit/d49972def684610e41b6ed1aeac42df6be662d80

**Comment by saeideng** [comment]
goods
just , description does not show now
do we really need to use HelpCommand ?

**Comment by dereuromark** [comment]
@markstory The whole purpose of such a verbose list IMO is to have some context on them.
Check out how Symfony console does it:

```
 sync
  sync:data                                        Exports synchronized data into queues
 transfer
  transfer:databuilder:generate                    Generates data builders from databuilder XML definition files
  transfer:generate                                Generates transfer objects from transfer XML definition files
  transfer:validate                                Validates transfer XML definition files
 translator
```

I am in general not a big fan of not having this a single command entry anymore with subcommands that show just as it has been in 2.x. But if we go this way I agree that having some more verbose output here is at least helpful when we use so much redundancy/space on the CLI.

**Comment by saeideng** [comment]
>Are you hoping to see a description of each command in the output of cake -h?

I point was for description of EntryCommand
and I understood why it does not show it

if we want description of each command we should first fix `HelpCommand`
now `HelpCommand` can not good deal with other Command like this `EntryCommand`
for reducing code I think we can fix HelpCommand to accept/handle help/entry commands

**Comment by saeideng** [comment]
problem with description for each command is we have to call `getOptionParser()` for each

**Comment by saeideng** [comment]
another choice is dont using HelpCommand 
```
# bin/cake bake --help
Available Commands:

 - bake all
 - bake behavior
 - bake cell
 - bake command
 - bake component
 - bake controller
 - bake controller all
 - bake fixture
 - bake fixture all
 - bake form
 - bake helper
 - bake mailer
 - bake middleware
 - bake model
 - bake model all
 - bake plugin
 - bake shell
 - bake shell_helper
 - bake task
 - bake template
 - bake template all
 - bake test

Bake generates code for your application. Different types of classes can
be generated with the subcommands listed below. For example run
bake controller --help to learn more about generating a
controller.

Usage:
cake bake [-h] [-q] [-v]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.

Older Shell based tasks will not be listed here, but can still be run.
```

let me know if you agree with this ^^

**Comment by markstory** [comment]
@saeideng Adding an entry point command could be useful for providing a nicer ux. There is an interface that enables a command to get the CommandCollection. That would let you get the 'subcommands' programmatically which would be good for when users add their own commands to bake.

**Pull request merged**
