### PR TITLE
Fixed return type issue

### PR DESCRIPTION
**Pull request by rochamarcelo**
Tested on linux - PHP 7.2.13

Error: Return value of Bake\Shell\Task\SimpleBakeTask::main() must be of the type integer or null, none returned

### CODE REVIEW

**Comment by markstory** [comment]
Looks like you have some trailing whitespace.

**Comment by saeideng** [comment]
we can remove return types from 
```php
BakeTask.php //public function main()
SimpleBakeTask.php //public function main(?string $name = null): ?int
TemplateTask.php //public function main(): ?int
```

`BakeTask` does not have any return types 
this is not force from core , but these should have same return type

**Comment by rochamarcelo** [comment]
We could return static::CODE_SUCCESS instead of null. What do you think?

**Comment by markstory** [comment]
@rochamarcelo That sounds like a good idea to me.

**Pull request merged**
