### PR TITLE
Allow using "Command/Bake" subfolder for bake commands.

### PR DESCRIPTION
**Pull request by ADmad**
If this subfolder exists, bake plugin will only use commands under that
directory as bake commands by default and will not check the command
files directly under "Command" folder.

### CODE REVIEW

**Comment by ADmad** [comment]
@markstory Which the default naming fix I need in previous command, does bake even need to iterator over the commands classes now since `BasePlugin::console()` already does that?

**Comment by ADmad** [comment]
To answer myself base plugin needs it's own command scanner as `BasePlugin`'s scanner adds plugin commands with plugin prefix.

**Comment by ADmad** [comment]
A new minor release would be better suited for this change.

**Comment by markstory** [comment]
> To answer myself base plugin needs it's own command scanner as BasePlugin's scanner adds plugin commands with plugin prefix.

Yep prefix fixing is one of the reasons.

**Pull request merged**
