### PR TITLE
Update brick/var-exporter to 0.5.0 and fix deprecations.

### PR DESCRIPTION
**Pull request by nicosp**
I took the liberty to update the PHP version for the code generation to 8.1 because it's also the minimum version for CakePHP 5.x.

### CODE REVIEW

**Comment by dereuromark** [comment]
I does block apps from updating that still require/use v4 (even as non primary dependency)
But I think blocking isn't as bad as BC breaking and as such this change seems like a pragmatic way of moving the dependency (usage) forward.
:+1:

**Comment by ADmad** [comment]
Only potential issue I see is someone using the removed VarExporter constants in their custom bake code. We can target this to `3.next` to be safe.

**Comment by ADmad** [comment]
@nicosp Please re-target this to `3.next` branch.

**Comment by dereuromark** [comment]
Also

    brick/varexporter         0.5.0      requires         nikic/php-parser (^5.0) 
    
Currently 4.x afaik

So better to have that clearly released as such :)

**Pull request closed without merging**
