### PR TITLE
Update use of deprecate File and Folder classes

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
php7.4 doesnt like the changes maybe?

```
There were 3 errors:
1) Bake\Test\TestCase\Command\PluginCommandTest::testMainBakePluginContents
file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:270
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:88
2) Bake\Test\TestCase\Command\PluginCommandTest::testMainVendorName
file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:270
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:115
3) Bake\Test\TestCase\Command\PluginCommandTest::testMainVendorNameCasingFix
file_get_contents(): read of 8192 bytes failed with errno=21 Is a directory
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:270
/home/travis/build/cakephp/bake/tests/TestCase/Command/PluginCommandTest.php:127
```

**Comment by ADmad** [comment]
@dereuromark The behavior of `file_get_contents()` changed in 7.4. Earlier it didn't throw explicit error if the path was for a directory, just returned false.

**Comment by dereuromark** [comment]
Is no one fixing stickler/CS?^^

> Expected 1 space before ., but 12 found

false positive

**Comment by markstory** [comment]
@dereuromark I can get the stickler warnings fixed. Our configuration doesn't currently use the right code sniffer version.

**Comment by ADmad** [comment]
Stickler aside, this is good to merge.

**Pull request merged**
