### PR TITLE
Add parameter type

### PR DESCRIPTION
**Pull request by thinkingmedia**
Adds param type for routes.

Makes the bake consistent with the app template.

https://github.com/cakephp/app/blob/master/config/routes.php

### CODE REVIEW

**Comment by dereuromark** [comment]
You will have to adjust the comparison test files:
https://travis-ci.org/cakephp/bake/jobs/122517283

**Comment by thinkingmedia** [comment]
@dereuromark oops, I just used GitHub's editor. I'll setup the build locally as I have other PRs to do later.

**Comment by thinkingmedia** [comment]
done.

**Comment by dereuromark** [comment]
:+1:

**Comment by markstory** [comment]
Thanks :+`:

**Pull request merged**
