### PR TITLE
Use stable releases

### PR DESCRIPTION
**Pull request by dereuromark**
Final thing for beta release.

### CODE REVIEW

**Comment by dereuromark** [comment]
> There were 46 errors:
1) Bake\Test\TestCase\Command\AllCommandTest::testExecute
Twig\Error\SyntaxError: Unexpected token "name" of value "if" ("end of statement block" expected).

That doesnt look good @WyriHaximus 
We probably need some upgrade guide for existing code.

**Comment by WyriHaximus** [comment]
@dereuromark let me have a look. Did a full plugin bake yesterday without any issues while testing this in the skeleton.

**Comment by WyriHaximus** [comment]
@dereuromark ok quick look gave me one thing that slipped through on my end and the other is a removed feature (:scream:) https://github.com/cakephp/bake/blob/master/templates/bake/Model/table.twig#L71 => https://github.com/twigphp/Twig/blob/3.x/CHANGELOG#L15

**Comment by ADmad** [comment]
PR #631

**Pull request closed without merging**
