### PR TITLE
Get FQCN instead of assuming it's a core behavior.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
Looks good.

**Comment by markstory** [comment]
Looks good. Tests will need to be updated though.

**Comment by ADmad** [comment]
Tests are fine, the code needed to be tweaked. My initial patch failed due to the fact that core behaviors are under `ORM/Behavior` instead of `Model/Behavior`.

This makes me wonder if this difference in namespace should be handled inside `App::className()` itself instead of [Behavior::_resolveClassName()](https://github.com/cakephp/cakephp/blob/d7cf3e7a1dde15ed9516b9932f6c436b4cd973ec/src/ORM/BehaviorRegistry.php#L92).

**Comment by markstory** [comment]
@ADmad `App::className()` is already pretty complex, perhaps behavior class resolution could have a public method on the BehaviorRegistry?

**Comment by ADmad** [comment]
> perhaps behavior class resolution could have a public method on the BehaviorRegistry?

And be static too? Wouldn't want to instantiate registry just to generate classname.

**Comment by markstory** [comment]
A static method should be ok.

**Pull request merged**
