### PR TITLE
Fix up relations in annotations.

### PR DESCRIPTION
**Pull request by dereuromark**
This is a first shot at https://github.com/cakephp/bake/issues/323

Also needed for IdeHelper to generate more correct output (refs https://github.com/dereuromark/cakephp-ide-helper/issues/5).

### CODE REVIEW

**Comment by dereuromark** [comment]
Anyone able to lend me a hand here to get things merged?
Not sure why it worked for me, but the tests fail.

**Comment by ndm2** [comment]
If you wanted to avoid pollution, then maybe a helper method that builds association info might be an option too. This could easily be extended with various other details in the future with interfering with other code that uses the bare association data.

```php
public function getAssociationInfo(array $associations)
{
	$info = [];

	$namespace = Configure::read('App.namespace');
	foreach ($associations as $type => $assocs) {
		foreach ($assocs as $assoc) {
			$name = isset($assoc['className']) ? $assoc['className'] : $assoc['alias'];
			$targetClass = $namespace . '\Model\Table\\' . $name . 'Table';

			$info[$assoc['alias']] = [
				'targetFqn' => '\\' . $targetClass
			];
		}
	}

	return $info;
}
```

```php
$targetFqn = $associationInfo[$assoc['alias']]['targetFqn'];
$annotations[] = "@property {$targetFqn}|\Cake\ORM\Association\\{$typeStr} \${$assoc['alias']}";
```

Or maybe go the kinda breaking change way, and change the `$associations` structure so that the association details and additional info are separated, like

```php
[
	'belongsToMany' => [
		'Products' => [
			'info' => [
				targetFqn' => '\App\Model\Table\ProductsTable'
			],
			'association' => [
				'foreignKey' => 'category_id',
				'targetForeignKey' => 'product_id',
				'joinTable' => 'categories_products'
			]
		]
	]
]
```

**Comment by dereuromark** [comment]
@ndm2 Do you want to make an alternative PR with your improved version?
You can also put commits on top of this one, if you want to.

**Comment by ndm2** [comment]
It's not that I really really really want to, but I can do it if I find a little more free time the next days :)

**Pull request closed without merging**
