### PR TITLE
Correct plugin generation for vendored plugins.

### PR DESCRIPTION
**Pull request by markstory**
Add additional template variables and templates to handle vendor plugins correctly.

Refs cakephp/cakephp#7062

### CODE REVIEW

**Comment by antograssiot** [comment]
@markstory didn't tested it yet but it looks strange to me that the `_modifyAutoloader()` function are unchanged because the main application composer.json would need to be update to `Company\\Example\\ `?

**Comment by markstory** [comment]
@antograssiot I missed that as its not in the test cases. I'll get that updated tonight.

**Comment by markstory** [comment]
@antograssiot Fixed :smile:

**Comment by antograssiot** [comment]
Looks good to me :+1:

**Comment by lorenzo** [comment]
Great job!

**Pull request merged**
