### PR TITLE
Don't assume there will always be a bootstrap file

### PR DESCRIPTION
**Pull request by alysson-azevedo**
Apply patch of the issue #42

### CODE REVIEW

**Comment by markstory** [comment]
Looks good, but [tests need to be updated](https://travis-ci.org/cakephp/bake/jobs/200232781)

**Comment by alysson-azevedo** [comment]
Yeah. I added this piece of code here on github because I was just looking the tests/bootstrap.php template, that is missing when we bake a plugin (see #307).

Latter i'll fork this repo and see if i'll be able to write the tests (i'm still learning).

**Comment by dereuromark** [comment]
Do we still need that?
IMO those can very well assume that there is at least a core file.
I vote for closing this.

**Comment by alysson-azevedo** [comment]
Ok, i'll see if i can update the tests.

**Comment by ADmad** [comment]
@markstory Is this good to merge?

**Pull request merged**
