### PR TITLE
Use global event manager for view

### PR DESCRIPTION
**Pull request by WyriHaximus**
@ADmad When you work on a fix regarding the event manager, this was the first thing I tried.

### CODE REVIEW

**Comment by ADmad** [comment]
@WyriHaximus I don't think this is necessary. Every event is dispatched to listeners of local as well as global event manager so passing global instance to the view class is not necessary.

As you pointed out earlier the problem is due to the fact that `TestCase::setUp()` resets the global instance hence the listeners set earlier by `TwigView`'s bootstrap are lost.

**Comment by WyriHaximus** [comment]
👍 just figured it might have been interesting 😄

**Comment by ADmad** [comment]
No problem, I sorted out the event issue in tests. Just a couple of issues left to fix in the templates.

**Comment by WyriHaximus** [comment]
Ye I have been monitoring the progress of the twig PR and it is coming along nicely 👍

**Pull request closed without merging**
