### PR TITLE
Correct the template override docs.

### PR DESCRIPTION
**Pull request by markstory**
Applications and themes have different paths for overrides. Refs #736

### CODE REVIEW

**Comment by othercorey** [comment]
What path/use did we leave this part of the path manipulation in for? There was one situation in either application override or plugin override that used this even after moving everything to use the `Bake.` prefix.

https://github.com/cakephp/bake/blob/master/src/View/BakeView.php#L143

**Comment by markstory** [comment]
> What path/use did we leave this part of the path manipulation in for? There was one situation in either application override or plugin override that used this even after moving everything to use the Bake. prefix.

That looks like it is for bake theme plugins.

**Review by connect232 — COMMENTED** [review]
Thanks for looking into this.

I think the directory should be templates/plugin/Bake/ taking away the 's' in plugins.

**Comment by othercorey** [comment]
Fixed the plugin directory name in application override.

**Pull request merged**
