### PR TITLE
Allow setting default theme through Configure.

### PR DESCRIPTION
**Pull request by ADmad**

### CODE REVIEW

**Comment by dereuromark** [comment]
:+1: always bothered me :)

**Comment by ADmad** [comment]
> always bothered me

Wish you had done something about it earlier and saved me the trouble :laughing:

**Comment by dereuromark** [comment]
Haha, I cant take all the credit.
And technically I already did so 2 years ago for my own bake template afaik: https://github.com/cakephp/bake/issues/222

PS: I usually make the whole config array Configure-able by the way, but I guess this is the most pressing one, so maybe this suffices already for most.

**Comment by ADmad** [comment]
> I usually make the whole config array Configure-able by the way..

Yeah, having the possibility in core itself would be nice but I too don't want to get into that right now.

**Comment by markstory** [comment]
Nice work!

**Comment by markstory** [comment]
Should the documentation also be updated for this?

**Comment by ADmad** [comment]
I'll make a PR for the docs

**Comment by ADmad** [comment]
Oh well, this change doesn't work in practice. I had assumed the defaults set for the shell would be passed to the `BakeTemplateTask`, but they don't.

While I can easily fix this issue by reading default through `Configure::read()` in `BakeTemplateTask` too, this is something we should consider fixing in general.

**Pull request merged**
