### PR TITLE
Add missing parent call for Table::initialize().

### PR DESCRIPTION
**Pull request by dereuromark**
Closes https://github.com/cakephp/bake/issues/120

### CODE REVIEW

**Comment by dereuromark** [comment]
Is there a way to remove that whitespace noise in the bake templates when generating?

**Comment by AD7six** [comment]
It fails because bakes output contains extra whitespace - the correct fix is to fix the output, looks to me like [this](https://github.com/cakephp/bake/blob/master-table/src/Template/Bake/Model/table.ctp#L147) is responsible:

    <%= "            " . implode("\n            ", $validationMethods) %>

There shouldn't be any "echo whitespace" logic in these templates, only echo statements at the right indentation level.

**Comment by dereuromark** [comment]
Or running a trim right on the generated code on a per row level.
Either way, the generated code shouldn't contain whitespace noise.

**Comment by AD7six** [comment]
> Or running a trim right on the generated code on a per row level.

I don't want that kind of logic - the template is right, or it's not. not mostly-right with magic applied. There'll be cases where you want/expect trailing whitespace and that'd prevent it.

**Comment by markstory** [comment]
Seems fine one the tests pass.

**Comment by dereuromark** [comment]
Feel free to fix the unrelated whitespace issue either as commits on top or separate PR.
Then this one will be fine to merge.

**Comment by AD7six** [comment]
@dereuromark it's changes in this pr that cause the test fails (it previously matched output, unrelated changes [to the test file in this PR](https://github.com/cakephp/bake/pull/124/files#diff-db1cb4ba7b04ad8856a4812ab4fe2a8aL35) make it fail).

As I've [mentioned before](https://github.com/cakephp/bake/pull/104#issuecomment-107087170) its easy to get the test output to match expectations - I can fix the now-apparent bad template later/tomorrow.

**Pull request merged**
