### PR TITLE
Add MIT as default license

### PR DESCRIPTION
**Pull request by dereuromark**
Closes https://github.com/cakephp/bake/issues/348

### CODE REVIEW

**Comment by markstory** [comment]
Looks like tests need to be updated.

**Comment by ADmad** [comment]
Should a LICENSE.txt also be added?

**Comment by inoas** [comment]
And why would we make that decision? What about "See License.txt"?

**Comment by dereuromark** [comment]
I fixed the test. This should be mergable as is.
We can have a follow up PR with the license txt file or some other reference to what @ionas suggested.

**Pull request merged**
