### PR TITLE
Table method annotations

### LINKED ISSUE #627: DocBlockHelper for Table is outdated
When baking a table classes the @method declarations are outdated. Should these be fixed in the DocBlockHelper ?

e.g.:
```php
 * @method \App\Model\Entity\Article get($primaryKey, $options = [])
 * @method \App\Model\Entity\Article newEntity(array $data, array $options = [])
 * @method \App\Model\Entity\Article newEmptyEntity()
 * @method \App\Model\Entity\Article[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Article|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Article saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Article[]|false saveMany(iterable $entities, $options = [])
 * @method \App\Model\Entity\Article[] saveManyOrFail(iterable $entities, $options = [])
 * @method \App\Model\Entity\Article patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Article[] patchEntities(iterable $entities, array $data, array $options = [])
 * @method \App\Model\Entity\Article findOrCreate($search, callable $callback = null, $options = [])
```

`delete`, `deleteMany` and `deleteManyOrFail` are missing as well.

### PR DESCRIPTION
**Pull request by swiffer**
https://github.com/cakephp/bake/issues/627

### CODE REVIEW

**Comment by dereuromark** [comment]
9 tests Have to be adjusted .

**Comment by swiffer** [comment]
yepp, I'll do later today!

**Comment by dereuromark** [comment]
3 fails left

I backported it for 3.x in the IdeHelper in https://github.com/dereuromark/cakephp-ide-helper/pull/165

**Comment by swiffer** [comment]
ah, these had been skipped locally - on it

**Pull request merged**
