### PR TITLE
new design generators

### PR DESCRIPTION
**Pull request by mtkocak**

### CODE REVIEW

**Comment by mtkocak** [comment]
https://github.com/cakephp/cakephp/issues/6679#issuecomment-107060805

**Comment by lorenzo** [comment]
You will probably need to update the tests

**Comment by ADmad** [comment]
Shouldn't this target 1.1 branch?

**Comment by mtkocak** [comment]
should I change the branch?

**Comment by ADmad** [comment]
@mtkocak There's already a 1.1 branch. You just need to target your PR to it instead of master.

**Comment by mtkocak** [comment]
umm sorry about that, I did create a new branch but pull request gone to master I think. I will try to change

**Comment by josegonzalez** [comment]
@mtkocak can you redo the pr against 1.1? :)

**Comment by ADmad** [comment]
@josegonzalez She already has, #104

**Comment by josegonzalez** [comment]
Heh yeah just saw that, my bad!

**Pull request closed without merging**
