### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by mik-laj**
Hello

Web accessibility is important, so today i add a scope attribute to genrated table.
http://webaim.org/techniques/tables/data

Thanks in advance.

### CODE REVIEW

**Comment by antograssiot** [comment]
@mik-laj tests will also need to be updated

**Comment by thinkingmedia** [comment]
`scope` is a deprecated attribute in **HTML5**

See the HTML5 specs of obsolete features.

https://www.w3.org/TR/html5/obsolete.html

**Comment by mik-laj** [comment]
`scope` is deprecated only for `td`.  For `th` is still valid.

**Comment by dereuromark** [comment]
That seems to be true.

**Comment by thinkingmedia** [comment]
I'm googling on this now. I've never heard of scope before, but I'm thinking that we should use `area` attributes if we want to support accessibility. So far, Mozilla and W3 have conflicting specs on the topic. One of the reasons I find these hidden attributes so difficult to use.

**Comment by thinkingmedia** [comment]
Okay, I think I'm figuring this out.

Here's a good spec on the role attribute in HTML5.

https://www.w3.org/wiki/PF/XTech/HTML5/RoleAttribute

Here is a spec that explains all the different role attributes, and how they are related to widgets.

https://www.w3.org/TR/2008/WD-wai-aria-20080806/#roles

For tables, there are three role attributes.

"gridcell", "rowheader" and "columnheader"

So I think `scope="col"` should be changed to `role="columnheader"`, and `scope="row"` should be changed to `role="rowheader"`.

Actually, I think rowheader is just for when a `<tr>` has an inner `<th>`.

**Comment by thinkingmedia** [comment]
Here's the start of role attributes for grids.

https://www.w3.org/TR/2008/WD-wai-aria-20080806/#grid

I think that makes for sense now that I read it.

**Comment by thinkingmedia** [comment]
That wasn't the latest document in the links.

https://www.w3.org/TR/wai-aria/

**Comment by thinkingmedia** [comment]
Here is the latest specs for `role="grid"` and the others.

https://www.w3.org/TR/wai-aria/roles#grid

Sorry for the spam comments.

**Comment by dereuromark** [comment]
So all good to be merged then?

**Pull request merged**
