### PR TITLE
folder name should be CamelCase

### PR DESCRIPTION
**Pull request by rrd108**
lowercase bake as a folder name is ignored by the bake command

### CODE REVIEW

**Comment by dereuromark** [comment]
The core ones are not: https://github.com/cakephp/bake/tree/master/templates/bake
Also mine are not : https://github.com/dereuromark/cakephp-setup/tree/master/templates/bake / https://github.com/spryker/cakephp-statemachine/tree/master/templates/bake

There must be some casing issue underneath then. as the lowercase bake should be correct IMO for the filesystem naming.
So this is most likely a bug for app level where the folder lookup doesn't work as documented.

**Comment by markstory** [comment]
The directory name used in the view is also lower cased https://github.com/cakephp/bake/blob/master/src/View/BakeView.php#L33

**Comment by garas** [comment]
`templates/plugin/Bake/` is generic path to [override plugin templates](https://book.cakephp.org/4/en/plugins.html#overriding-plugin-templates-from-inside-your-application).

`templates/bake` is Bake specific path to override templates.

Both methods should work, but preferred is probably the second one.

Docs should be use one of method to avoid confusion.

**Comment by dereuromark** [comment]
That explains it
I would then think we document the latter.

**Pull request merged**
